name: Checkmarx One Code Scanning Alerts
on:
  push:
    branches: 
      - main
      - master
      - dev
      - Terraform-project-1
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [ "Terraform-project-1" ]

permissions:
  contents: read
  pull-requests: write

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Checkmarx One scan
        uses: checkmarx/ast-github-action@main
        with:
          base_uri: https://ind.ast.checkmarx.net
          cx_client_id: ${{ vars.CLIENT_ID }}
          cx_client_secret: ${{ secrets.SECRET }}
          cx_tenant: ${{ vars.TENANT }}
          scan_params: "--sast-incremental --file-filter \"!*.tf\""
          github_token: ${{ github.token }}
          repo_name: ${{ github.event.repository.name }}
          namespace: ${{ github.repository_owner }}
          pr_number: ${{ github.event.number }}

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: cx_result.sarif
