name: checkmarx Scan Scheduler
on: 
  schedule:
    - cron: "*/2 * * * *"

jobs: 
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Checkmarx AST Github Action
        uses: Checkmarx/ast-github-action@2.0.23
        with:
          base_uri: https://ast.checkmarx.net
          cx_tenant: ps_na_miguel_gonzalez
          cx_client_id: ${{ secrets.CLIENT_ID }}
          cx_client_secret: ${{ secrets.SECRET }}
          project_name: ${{ github.repository }}
          branch: ${{ github.head_ref || github.ref }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repo_name: ${{ github.event.repository.name }}
          namespace: ${{ github.repository_owner }}
          pr_number: ${{ github.event.number }}
