name: Checkmarx Scan

on:
  workflow_dispatch:  # Allows manual triggering of the workflow
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight

jobs:
  checkmarx-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run Checkmarx Scan
      env:
        CX_REFRESH_TOKEN: ${{ secrets.CX_API_KEY }}
        CX_PROJECT_ID: ${{ secrets.CX_PROJECT_ID }}
        CX_ORIGIN: GitHub Actions
        CX_INCREMENTAL_SCAN: "false"
        CX_PROJECT_NAME: abhishekmurthy72/Terraform_project
        CX_REPO_URL: https://github.com/abhishekmurthy72/Terraform_project
        CX_BRANCH: Terraform-project-1
        CX_USERNAME: ${{ secrets.GIT_USERNAME }}
        CX_API_KEY: ${{ secrets.GITHUB_TOKEN }}
      run: |
        python scheduler.py
