name: Python CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'  # Specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install .  # Install project dependencies including checkmarx-python-sdk

    - name: Verify SDK installation
      run: |
        python -c "import checkmarx_python_sdk; print(checkmarx_python_sdk.__version__)"

    - name: Run tests
      run: |
        # Replace with your actual test command, if any
        pytest  # Example assuming you use pytest for testing

    # Add more steps as needed, such as deployment steps or additional testing

