name: vorpal-reviewdog-changeFiles
on: [pull_request]
jobs:
  vorpal:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          separator: ','
        
      - name: Vorpal with reviewdog
        uses: checkmarx/vorpal-reviewdog-github-action@v2.0.0
        with:
          source_path: "${{ steps.changed-files.outputs.all_changed_files }}"
          filter_mode: added
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-check , github-pr-review
          level: error
          fail_on_error: true
